# profile for testing the workflow on slurm

# use slurm as executor
executor: slurm

# maximum number of jobs
jobs: 20

# use conda environments
use-conda: true

# rerun incomplete jobs
rerun-incomplete: true

# Sets how long snakemake waits for output files after job completion (in seconds). Recommended for networked file systems.
latency-wait: 60

# default resources for all rules
default-resources:
    mem_mb: 4000
    runtime: 3h
    threads: 4

# specific resources for certain rules
set-resources:
    getorganelle:
        mem_mb: 64000
        runtime: 24h
        threads: 6
    blobtools_create:
        mem_mb: 8000
