
executor: slurm
jobs: 4
use-conda: true
rerun-incomplete: true
printshellcmds: true

default-resources:
    slurm_account: cropdiv-acc
    slurm_partition: short
    mem: "4GB"
    cpus_per_task: 2
    threads: 2
    runtime: "6h"

set-resources:
    fastp:
        mem: "4G"
    getorganelle:
        mem: "10G"
        cpus_per_task: 6
        threads: 6
        slurm_partition: short
